### ISSUE TITLE
CUDA 报错：CUBLAS_STATUS_NOT_INITIALIZED 触发于 F.linear（TorchScript + RWKV7 批量推理 + State 复用）

### ISSUE THREAD

**Issue by AUXStar** [RWKV-Vibe/rwkv_lightning#8]
# Issue 标题
CUDA报错：`CUBLAS_STATUS_NOT_INITIALIZED` 触发于 F.linear（TorchScript + RWKV7批量推理 + State复用）

# Issue 正文（纯Markdown 中文，直接粘贴）
## 问题描述
在 `rwkv_lightning` 项目中，开启 **RWKV7 批量推理 + State状态池复用**，使用Robyn接口服务时，稳定复现CUDA致命错误：
```
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasLtMatmulAlgoGetHeuristic(...)`
```
报错发生在 TorchScript 解释器内部，固定出现于 TMix 前向逻辑的 `F.linear` 矩阵乘法调用。

## 运行环境
- PyTorch：pytorch-cu130
- 模型：RWKV7
- 推理模式：批量续推 / 连续批处理 / State状态复用
- 后端服务：Robyn API
- 硬件：NVIDIA 5070ti laptop windows11 wsl debian
```
Sat Mar 28 13:10:06 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 595.45.03              Driver Version: 595.71         CUDA Version: 13.2     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 5070 ...    On  |   00000000:01:00.0 Off |                  N/A |
| N/A   48C    P8              6W /  132W |    5908MiB /  12227MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A            2519      C   /python3.13                           N/A      |
+-----------------------------------------------------------------------------------------+
```

## 复现步骤
1. 启动项目后端，开启批量推理 & State复用功能
2. 调用接口：`/v2/chat/completions`、`/v3/chat/completions`
3. 触发模型分支 `forward_seq_batch` / `forward_seq`
4. 程序在 `RWKV_x070_TMix_seq_batch` / `RWKV_x070_TMix_seq` 内的 `F.linear` 直接崩溃

## 核心报错日志
```txt
Error in async generator: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/home/njzy/rwkv_agent/rwkv_lightning/infer/rwkv_batch/rwkv7.py", line 334, in forward_seq_batch
                xx, v_first = RWKV_x070_TMix_seq_batch(...)
  File "/home/njzy/rwkv_agent/rwkv_lightning/infer/rwkv_batch/rwkv7.py", line 472, in RWKV_x070_TMix_seq_batch
    w = F.linear(torch.tanh(F.linear(xw, w1)), w2, bias=w0)
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasLtMatmulAlgoGetHeuristic(ltHandle, computeDesc.descriptor(), Adesc.descriptor(), Bdesc.descriptor(), Cdesc.descriptor(), Cdesc.descriptor(), preference.descriptor(), 1, &heuristicResult, &returnedResult)`
```

## 已尝试的修复方案（均无效）
1. 完全禁用 `torch.compile`，替换为空匿名函数
2. 清空PyTorch编译缓存：删除 `~/.cache/torch`、`~/.cache/torchinductor`
3. 配置环境变量：
```bash
export CUDA_LAUNCH_BLOCKING=1
export CUDA_MODULE_LOADING=LAZY
export PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:32
export TORCHDYNAMO_DISABLE=1
```
4. 关闭cuDNN、关闭TF32加速
5. 强制设置批量大小 `batch_size = 1`
6. 重启服务、清空所有State状态池
7. 重装匹配CUDA版本的PyTorch

## 补充说明
1. 显存充足，占用率低于50%，非显存溢出导致；
2. 非批量的单条推理路径可正常运行，无报错；
3. 仅 **批量推理 + State复用** 组合会触发崩溃；
4. 报错入口固定，每次都卡在 `F.linear` 矩阵乘法位置。

**Comment by Alic-Li** [comment]
Hi 我今天也似乎遇到了这个问题,发现只要 pip install torch torchvision --upgrade 一下,然后用包管理器更新一下系统就行,我也是在PyTorch version: 2.10.0+cu130触发的,发现更新到PyTorch version: 2.11.0+cu130就好啦

**Comment by AUXStar** [comment]
已解决！谢谢大佬
